const NF = window.EXRiscoFirebase;
const { writeBatch: netBatch, orderBy: netOrderBy, startAt: netStartAt, endAt: netEndAt, limit: netLimit } = NF;
state.networkResults = [];
state.pendingNetworkRecord = null;
state.pendingImportData = null;

function netUi() {
  if (!$('#netStyles')) {
    const s = document.createElement('style'); s.id = 'netStyles';
    s.textContent = '.net-search{display:flex;gap:8px;align-items:end}.net-search .field{flex:1}.net-results{display:grid;gap:9px;margin-top:14px}.net-row{display:flex;justify-content:space-between;gap:12px;padding:12px;border:1px solid var(--border);border-radius:12px}.net-row strong,.net-row span{display:block}.net-row span{font-size:9px;color:var(--muted);margin-top:3px}.net-posto{color:var(--primary)!important;font-weight:800}.net-help{margin-top:9px;padding:9px 11px;border-radius:9px;background:#f3f8f7;color:var(--muted);font-size:9px}.net-progress{height:8px;background:#e7efee;border-radius:99px;overflow:hidden;margin-top:12px}.net-progress i{display:block;height:100%;width:0;background:var(--primary)}@media(max-width:700px){.net-search,.net-row{display:grid}.net-row .btn{width:100%}}';
    document.head.appendChild(s);
  }
  if (!$('#patientCns')) {
    const cpf = $('#patientCpf')?.closest('.field');
    if (cpf) { const l=document.createElement('label'); l.className='field'; l.innerHTML='<span>CNS</span><input id="patientCns" inputmode="numeric" maxlength="15" placeholder="000000000000000">'; cpf.after(l); $('#patientCns').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,15); }
  }
  if (!$('#networkSearchBtn')) {
    const b=document.createElement('button'); b.id='networkSearchBtn'; b.className='btn ghost'; b.type='button'; b.textContent='⌕ Buscar cidadão';
    $('.topbar-actions')?.insertBefore(b,$('#quickAddPatientBtn')); b.onclick=openNetworkSearch;
  }
  if (!$('#importBaseBtn')) {
    const b=document.createElement('button'); b.id='importBaseBtn'; b.className='btn ghost admin-only hidden'; b.type='button'; b.textContent='⇧ Importar base de cidadãos';
    $('#view-postos .section-actions')?.appendChild(b); b.onclick=openBaseImport;
  }
  if (!$('#networkSearchModal')) document.body.insertAdjacentHTML('beforeend',`<div id="networkSearchModal" class="modal hidden"><div class="modal-backdrop" data-close-modal="networkSearchModal"></div><div class="modal-dialog medium-dialog"><div class="modal-head"><div><span class="eyebrow">Rede municipal</span><h2>Buscar cidadão em todos os postos</h2></div><button class="icon-btn" data-close-modal="networkSearchModal">×</button></div><div class="modal-body"><form id="networkSearchForm" class="net-search"><label class="field"><span>Nome, CPF ou CNS</span><input id="networkSearchInput" autocomplete="off" placeholder="Digite o início do nome ou o documento completo"></label><button class="btn primary">Buscar</button></form><div class="net-help">A busca exibe somente identificação e unidade. Dados de acompanhamento de outro posto continuam protegidos.</div><div id="networkSearchResults" class="net-results"></div></div></div></div>`);
  if (!$('#importBaseModal')) document.body.insertAdjacentHTML('beforeend',`<div id="importBaseModal" class="modal hidden"><div class="modal-backdrop" data-close-modal="importBaseModal"></div><div class="modal-dialog medium-dialog"><div class="modal-head"><div><span class="eyebrow">Administrador</span><h2>Importar base inicial</h2></div><button class="icon-btn" data-close-modal="importBaseModal">×</button></div><div class="modal-body"><label class="field"><span>Arquivo JSON preparado</span><input id="importBaseFile" type="file" accept=".json,application/json"></label><div class="net-help">O arquivo fica no seu computador e é enviado diretamente ao Firebase; ele não é publicado no GitHub. Postos ausentes serão criados automaticamente.</div><div id="importBaseSummary" class="hint"></div><div id="importProgressWrap" class="hidden"><div class="net-progress"><i id="importProgressBar"></i></div><div id="importStatus" class="hint"></div></div><p id="importBaseError" class="form-error hidden"></p></div><div class="modal-foot"><div></div><div class="modal-actions"><button class="btn ghost" data-close-modal="importBaseModal">Cancelar</button><button id="runImportBtn" class="btn primary" disabled>Importar para o Firebase</button></div></div></div></div>`);
  $('#networkSearchForm').onsubmit=doNetworkSearch; $('#networkSearchResults').onclick=networkAction;
  $('#importBaseFile').onchange=readBaseFile; $('#runImportBtn').onclick=runBaseImport;
}

function openNetworkSearch(){ state.networkResults=[]; $('#networkSearchInput').value=''; $('#networkSearchResults').innerHTML='<div class="empty-state"><p>Digite nome, CPF ou CNS.</p></div>'; openModal('networkSearchModal'); setTimeout(()=>$('#networkSearchInput').focus(),50); }
async function doNetworkSearch(e){ e.preventDefault(); const v=$('#networkSearchInput').value.trim(), box=$('#networkSearchResults'); if(v.length<2){box.innerHTML='<div class="form-error">Digite pelo menos 2 caracteres.</div>';return;} box.innerHTML='<div class="empty-state"><p>Buscando...</p></div>'; try{state.networkResults=await findNetwork(v); renderNetwork();}catch(err){box.innerHTML=`<div class="form-error">${escapeHtml(firebaseMessage(err))}</div>`;} }
async function findNetwork(v){ const digits=v.replace(/\D/g,''), map=new Map(); if(digits.length>=11){ for(const field of ['cpfNormalizado','cnsNormalizado']){ const s=await getDocs(query(collection(db,'pacientes_index'),where(field,'==',digits),netLimit(20))); s.docs.forEach(d=>map.set(d.id,{id:d.id,...d.data()})); } } else { const t=normalizeText(v); const s=await getDocs(query(collection(db,'pacientes_index'),netOrderBy('nomeBusca'),netStartAt(t),netEndAt(t+'\uf8ff'),netLimit(30))); s.docs.forEach(d=>map.set(d.id,{id:d.id,...d.data()})); } return [...map.values()].sort((a,b)=>(a.nome||'').localeCompare(b.nome||'','pt-BR')); }
function renderNetwork(){ const box=$('#networkSearchResults'); if(!state.networkResults.length){box.innerHTML='<div class="empty-state"><p>Nenhum cidadão encontrado.</p></div>';return;} box.innerHTML=state.networkResults.map((x,i)=>{const own=state.profile.role==='admin'||x.postoId===state.profile.postoId; const docs=[x.cpf&&`CPF ${x.cpf}`,x.cns&&`CNS ${x.cns}`].filter(Boolean).join(' · ')||'Sem CPF/CNS'; let a='<span class="mini-badge">Outro posto</span>'; if(own&&x.acompanhamentoAtivo&&x.pacienteId)a=`<button class="btn primary small" data-net="open" data-i="${i}">Abrir acompanhamento</button>`; else if(own)a=`<button class="btn primary small" data-net="start" data-i="${i}">Iniciar acompanhamento</button>`; return `<div class="net-row"><div><strong>${escapeHtml(x.nome||'')}</strong><span>${escapeHtml(docs)} · Nasc. ${formatDate(x.dataNascimento)} · ${calculateAge(x.dataNascimento)} anos</span><span class="net-posto">${escapeHtml(x.postoNome||'Unidade não identificada')}${x.possivelDuplicadoRede?' · possível duplicidade':''}</span></div><div>${a}</div></div>`;}).join(''); }
function networkAction(e){ const b=e.target.closest('[data-net]'); if(!b)return; const x=state.networkResults[Number(b.dataset.i)]; if(!x)return; if(b.dataset.net==='open'){const p=state.patients.find(y=>y.id===x.pacienteId); if(!p)return showToast('Atualize a página e tente novamente.','error'); closeModal('networkSearchModal'); openPatient(p);}else{closeModal('networkSearchModal'); startNetworkPatient(x);} }
function startNetworkPatient(x){ state.pendingNetworkRecord=x; originalOpenPatient(null); $('#patientName').value=x.nome||''; $('#patientCpf').value=x.cpf||''; $('#patientCns').value=x.cns||''; $('#patientBirth').value=x.dataNascimento||''; $('#patientAge').value=`${calculateAge(x.dataNascimento)} anos`; if(state.profile.role==='admin')$('#patientPosto').value=x.postoId||''; $('#patientModalTitle').textContent='Iniciar acompanhamento'; }

async function identityConflict(cpf,cns,ignore=''){ for(const [field,val] of [['cpfNormalizado',cpf],['cnsNormalizado',cns]]) if(val){const s=await getDocs(query(collection(db,'pacientes_index'),where(field,'==',val),netLimit(5))); const hit=s.docs.find(d=>d.id!==ignore); if(hit)return{id:hit.id,...hit.data()};} return null; }
async function syncNetworkIndex(p,source=null){ if(!p?.id)return; const idx=source?.id||p.networkIndexId||p.id; const postoId=p.postoId||source?.postoId||''; const cns=String(p.cns||source?.cns||'').replace(/\D/g,''); await setDoc(doc(db,'pacientes_index',idx),{nome:p.nome||source?.nome||'',nomeBusca:normalizeText(p.nome||source?.nome||''),cpf:p.cpf||source?.cpf||'',cpfNormalizado:String(p.cpfNormalizado||source?.cpfNormalizado||'').replace(/\D/g,''),cns,cnsNormalizado:cns,dataNascimento:p.dataNascimento||source?.dataNascimento||'',postoId,postoNome:source?.postoNome||getPostoName(postoId),ativo:p.ativo!==false,acompanhamentoAtivo:p.ativo!==false,pacienteId:p.id,cadastroBase:source?.cadastroBase===true||p.cadastroBase===true,possivelDuplicadoRede:source?.possivelDuplicadoRede===true,grupoDuplicadoRede:source?.grupoDuplicadoRede||'',atualizadoEm:serverTimestamp()},{merge:true}); const patch={networkIndexId:idx}; if(cns){patch.cns=cns;patch.cnsNormalizado=cns;} await updateDoc(doc(db,'pacientes',p.id),patch); }
const originalOpenPatient=openPatient;
openPatient=function(p=null){state.pendingNetworkRecord=null;originalOpenPatient(p);netUi();$('#patientCns').value=p?.cns||'';};
const originalSavePatient=savePatient;
savePatient=async function(e){e.preventDefault(); const pending=state.pendingNetworkRecord,id=$('#patientId').value,name=$('#patientName').value.trim(),dob=$('#patientBirth').value,cpf=$('#patientCpf').value.replace(/\D/g,''),cns=$('#patientCns').value.replace(/\D/g,''); if(cns&&cns.length!==15)return showPatientError('O CNS deve conter 15 dígitos.'); if(!id){try{const hit=await identityConflict(cpf,cns,pending?.id||''); if(hit)return showPatientError(`Este cidadão já existe na base da rede e está vinculado a ${hit.postoNome||'outro posto'}. Use “Buscar cidadão”.`);}catch(err){return showPatientError(firebaseMessage(err));}} await originalSavePatient(e); if(!$('#patientModal').classList.contains('hidden'))return; let p=id?state.patients.find(x=>x.id===id):state.patients.find(x=>normalizeText(x.nome)===normalizeText(name)&&x.dataNascimento===dob&&(!cpf||x.cpfNormalizado===cpf)); if(!p)return; p.cns=cns;p.cnsNormalizado=cns; try{await syncNetworkIndex(p,pending);state.pendingNetworkRecord=null;}catch(err){showToast('Paciente salvo, mas a busca da rede não foi atualizada: '+firebaseMessage(err),'error');} };
if(typeof togglePatient==='function'){const originalToggle=togglePatient;togglePatient=async function(p){await originalToggle(p);const u=state.patients.find(x=>x.id===p.id);if(u)try{await syncNetworkIndex(u);}catch(err){console.warn(err);}};}

function openBaseImport(){if(state.profile.role!=='admin')return;state.pendingImportData=null;$('#importBaseFile').value='';$('#importBaseSummary').textContent='';$('#importBaseError').classList.add('hidden');$('#importProgressWrap').classList.add('hidden');$('#runImportBtn').disabled=true;openModal('importBaseModal');}
async function readBaseFile(e){try{const d=JSON.parse(await e.target.files[0].text());if(d.schema!=='exrisco-importacao-base-v1'||!Array.isArray(d.postos)||!Array.isArray(d.pacientes))throw Error('Arquivo incompatível.');state.pendingImportData=d;$('#importBaseSummary').textContent=`${d.postos.length} postos · ${d.pacientes.length.toLocaleString('pt-BR')} cidadãos · ${Number(d.resumo?.possiveisDuplicadosEntreUnidades||0)} grupos para revisão`;$('#runImportBtn').disabled=false;}catch(err){$('#importBaseError').textContent=err.message;$('#importBaseError').classList.remove('hidden');}}
async function runBaseImport(){const d=state.pendingImportData;if(!d||state.profile.role!=='admin')return;const err=$('#importBaseError'),bar=$('#importProgressBar'),status=$('#importStatus');err.classList.add('hidden');$('#runImportBtn').disabled=true;$('#importProgressWrap').classList.remove('hidden');try{const byName=new Map(state.postos.map(p=>[normalizeText(p.nome),p.id])),postoMap=new Map();for(const p of d.postos){const id=byName.get(normalizeText(p.nome))||p.id;postoMap.set(p.id,id);if(!byName.has(normalizeText(p.nome)))await setDoc(doc(db,'postos',id),{nome:p.nome,sigla:p.sigla||'',cnes:p.cnes||'',ativo:p.ativo!==false,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()},{merge:true});} const total=d.pacientes.length,size=450;let done=0;for(let off=0;off<total;off+=size){const batch=netBatch(db);for(const x of d.pacientes.slice(off,off+size)){const pd=d.postos.find(p=>p.id===x.postoId);batch.set(doc(db,'pacientes_index',x.id),{nome:x.nome,nomeBusca:normalizeText(x.nome),cpf:x.cpf||'',cpfNormalizado:String(x.cpfNormalizado||'').replace(/\D/g,''),cns:x.cns||'',cnsNormalizado:String(x.cnsNormalizado||'').replace(/\D/g,''),dataNascimento:x.dataNascimento||'',idadeReferencia:x.idade??null,postoId:postoMap.get(x.postoId)||x.postoId,postoNome:pd?.nome||x.postoNome||'',ativo:x.ativo!==false,cadastroBase:true,acompanhamentoAtivo:false,pacienteId:null,origemArquivo:x.origemArquivo||'',origemPagina:x.origemPagina||null,possivelDuplicadoRede:x.possivelDuplicadoRede===true,grupoDuplicadoRede:x.grupoDuplicadoRede||'',importadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()},{merge:true});}await batch.commit();done+=Math.min(size,total-off);const pct=Math.round(done/total*100);bar.style.width=pct+'%';status.textContent=`${done.toLocaleString('pt-BR')} de ${total.toLocaleString('pt-BR')} (${pct}%)`;await new Promise(r=>setTimeout(r,20));}await loadPostos();refreshPostoFilters();renderPostos();status.textContent=`Concluído: ${total.toLocaleString('pt-BR')} cidadãos.`;showToast('Base inicial importada com sucesso.');}catch(ex){console.error(ex);err.textContent=firebaseMessage(ex);err.classList.remove('hidden');$('#runImportBtn').disabled=false;}}

netUi();
